version: '3.8'

services:
  odb:
    build: image-odb
    container_name: 'odb'
    volumes:
      - ./apps:/apps
      - ./apps.cnf:/apps.cnf
    environment:
      ORIENTDB_ROOT_PASSWORD: 'root'
    ports:
      - '2424:2424'
      - '2480:2480'
  
  jupyter:
    build: image-jupyter
    container_name: 'jupyter'
    volumes:
      - ./apps:/apps
      - ./apps.cnf:/apps.cnf
    ports:
      - '80:8888'
    depends_on:
      - odb