version: '3.8'

services:
  odb:
    image: 'orientdb:3.1.1'
    container_name: 'odb'
    volumes:
      - ./scripts:/scripts
    environment:
      ORIENTDB_ROOT_PASSWORD: 'root'
    ports:
      - '2425:2424'
      - '2481:2480'
    command: './scripts/apply-config-odb.sh'
  
  jupyter:
    image: 'jupyter/scipy-notebook:latest'
    container_name: 'jupyter'
    volumes:
      - ./scripts:/scripts
    ports:
      - '80:80'
    depends_on:
      - odb
    command: './scripts/apply-config-jupyter.sh'